### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by NoHara42** [devhausleipzig/camp-8-midterm-group-1#22]
- [x] Use the NavigationLayout as a Layout for this page. #12 
- [x] Mount the UserInfo Component #10 
- [x] Mount the Search Input Component #8  
- [x] Mount the IconButton Component #11 
- [x] Mount the Upcoming Movies Carousel  #24 

https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/camp-8-midterm?node-id=1%3A4&t=kZhG2xEFN1x3WzUM-4
